- name: "Install app node"
  hosts: aula
  become: yes #autenticação
  vars:
    path_app: /usr/app
  tasks:
    - name: "1 - Criar diretório"
      file:
        path: "{{path_app}}"
        state: directory
        mode: '0755'

    - name: "2 - Instalar Unzip"
      package:
        name: 
          -unzip
        state: present

    - name: "3 - Download e Descompactar"
      unarchive:
        src: https://github.com/bgsouza/app_node2/archive/master.zip
        dest: "{{path_app}}"
        remote_src: yes

    - name: "4 - Compilando App" #npm instal

    - name: "5 - Gerenciador node pm2" 

    - name: "6 - Rodar a app" #roda e deixa disponível


    #1 - create dir in ansible no google
    #3 -downlos unzip file in ansible


